#lang plai

(print-only-errors)

(require "grammars.rkt")
(require "parser.rkt")
(require "desugar.rkt")
(require "interp.rkt")

;; Definición de expresiones.

(define expr1  'foo)
(define expr2  1729)
(define expr3  '{+ 1 2 3})
(define expr4  '{- 1 2 3})
(define expr5  '{* 1 2 3})
(define expr6  '{/ 1 2 3})
(define expr7  '{modulo 9 3})
(define expr8  '{expt 2 3})
(define expr9  '{add1 17})
(define expr10 '{sub1 29})
(define expr11 '{with {{a 2} {b 3}}
                  {+ a b}})
(define expr12 '{with {{a 2} {b {+ a a}}}
                  b})
(define expr13 '{with* {{a 2} {b {+ a a}}}
                  b})
(define expr14 '{with {{a a}}
                  a})
(define expr15 '{with {{b a}}
                  a})
(define expr16 '{fun {b h} {/ {* b h} 2}})
(define expr17 '{{fun {b h} {/ {* b h} 2}} 10 2})
(define expr18 '{{fun {p q} {if p p q}} true false})
(define expr19 '{{fun {p q} {if p q p}} false false})
(define expr20 '{{fun {x} {cond {{< x 10} 2} {{< x 20} 3} {else 4}}} 8})
(define expr21 '{{fun {x} {cond {{< x 10} 2} {{< x 20} 3} {else 4}}} 30})
(define expr22 '{not true})
(define expr23 '{with {{p true} {q false}} {not {and p {or p q}}}})
(define expr24 '{with* {{a 2} {b {/ a 0}}} 17})
(define expr25 '{{fun {x} 1} {sub1 {fun {x} x}}})

;; Pruebas parser :: parse

(test (parse expr1) (idS 'foo))
(test (parse expr2) (numS 1729))
(test (parse expr3) (opS + (list (numS 1) (numS 2) (numS 3))))
(test (parse expr4) (opS - (list (numS 1) (numS 2) (numS 3))))
(test (parse expr5) (opS * (list (numS 1) (numS 2) (numS 3))))
(test (parse expr6) (opS / (list (numS 1) (numS 2) (numS 3))))
(test (parse expr7) (opS modulo (list (numS 9) (numS 3))))
(test (parse expr8) (opS expt (list (numS 2) (numS 3))))
(test (parse expr9) (opS add1 (list (numS 17))))
(test (parse expr10) (opS sub1 (list (numS 29))))
(test (parse expr11) 
      (withS (list (binding 'a (numS 2)) (binding 'b (numS 3))) (opS + (list (idS 'a) (idS 'b)))))
(test (parse expr12)
      (withS (list (binding 'a (numS 2)) (binding 'b (opS + (list (idS 'a) (idS 'a))))) (idS 'b)))
(test (parse expr13)
      (withS* (list (binding 'a (numS 2)) (binding 'b (opS + (list (idS 'a) (idS 'a))))) (idS 'b)))
(test (parse expr14)
      (withS (list (binding 'a (idS 'a))) (idS 'a)))
(test (parse expr15)
      (withS (list (binding 'b (idS 'a))) (idS 'a)))
(test (parse expr16)
      (funS '(b h) (opS / (list (opS * (list (idS 'b) (idS 'h))) (numS 2)))))
(test (parse expr17)
      (appS (parse expr16) (list (numS 10) (numS 2))))
(test (parse expr18)
      (appS (funS '(p q) (ifS (idS 'p) (idS 'p) (idS 'q))) (list (boolS #t) (boolS #f))))
(test (parse expr19)
      (appS (funS '(p q) (ifS (idS 'p) (idS 'q) (idS 'p))) (list (boolS #f) (boolS #f))))
(test (parse expr20)
      (appS (funS '(x) 
                  (condS (list (condition (opS < (list (idS 'x) (numS 10))) (numS 2)) 
                               (condition (opS < (list (idS 'x) (numS 20))) (numS 3))
                               (else-cond (numS 4)))))
            (list (numS 8))))
(test (parse expr21)
      (appS (funS '(x) 
                  (condS (list (condition (opS < (list (idS 'x) (numS 10))) (numS 2)) 
                               (condition (opS < (list (idS 'x) (numS 20))) (numS 3))
                               (else-cond (numS 4)))))
            (list (numS 30))))
(test (parse expr22) (opS not (list (boolS #t))))
(test (parse expr23)
      (withS (list (binding 'p (boolS #t)) (binding 'q (boolS #f))) 
             (opS not 
                 (list (opS (elige 'and) (list (idS 'p) 
                       (opS (elige 'or) (list (idS 'p) (idS 'q)))))))))
(test (parse expr24)
      (withS* (list (binding 'a (numS 2)) (binding 'b (opS / (list (idS 'a) (numS 0)))))
              (numS 17)))
(test (parse expr25)
      (appS (funS '(x) (numS 1)) (list (opS sub1 (list (funS '(x) (idS 'x)))))))

;; Pruebas desugar :: desugar
(test (desugar (parse expr1)) (id 'foo))
(test (desugar (parse expr2)) (num 1729))
(test (desugar (parse expr3)) (op + (list (num 1) (num 2) (num 3))))
(test (desugar (parse expr4)) (op - (list (num 1) (num 2) (num 3))))
(test (desugar (parse expr5)) (op * (list (num 1) (num 2) (num 3))))
(test (desugar (parse expr6)) (op / (list (num 1) (num 2) (num 3))))
(test (desugar (parse expr7)) (op modulo (list (num 9) (num 3))))
(test (desugar (parse expr8)) (op expt (list (num 2) (num 3))))
(test (desugar (parse expr9)) (op add1 (list (num 17))))
(test (desugar (parse expr10)) (op sub1 (list (num 29))))
(test (desugar (parse expr11)) 
      (app (app (fun 'a (fun 'b (op + (list (id 'a) (id 'b))))) (num 2)) (num 3)))
(test (desugar (parse expr12)) 
      (app (app (fun 'a (fun 'b (id 'b))) (num 2)) (op + (list (id 'a) (id 'a)))))
(test (desugar (parse expr13)) 
      (app (fun 'a (app (fun 'b (id 'b)) (op + (list (id 'a) (id 'a))))) (num 2)))
(test (desugar (parse expr14)) (app (fun 'a (id 'a)) (id 'a)))
(test (desugar (parse expr15)) (app (fun 'b (id 'a)) (id 'a)))
(test (desugar (parse expr16)) 
      (fun 'b (fun 'h (op / (list (op * (list (id 'b) (id 'h))) (num 2))))))
(test (desugar (parse expr17))
      (app (app (fun 'b (fun 'h (op / (list (op * (list (id 'b) (id 'h))) (num 2))))) (num 10)) 
           (num 2)))
(test (desugar (parse expr18)) 
      (app (app (fun 'p (fun 'q (iF (id 'p) (id 'p) (id 'q)))) (bool #t)) (bool #f)))
(test (desugar (parse expr19)) 
      (app (app (fun 'p (fun 'q (iF (id 'p) (id 'q) (id 'p)))) (bool #f)) (bool #f)))
(test (desugar (parse expr20))
      (app (fun 'x 
                (iF (op < (list (id 'x) (num 10))) 
                    (num 2) 
                    (iF (op < (list (id 'x) (num 20))) (num 3) (num 4)))) 
           (num 8)))
(test (desugar (parse expr21))
      (app (fun 'x 
                (iF (op < (list (id 'x) (num 10))) 
                    (num 2) 
                    (iF (op < (list (id 'x) (num 20))) (num 3) (num 4)))) 
           (num 30)))
(test (desugar (parse expr22))
      (op not (list (bool #t))))
(test (desugar (parse expr23)) 
      (app (app (fun 'p 
                     (fun 'q 
                          (op not 
                              (list (op (elige 'and) (list (id 'p) 
                                    (op (elige 'or) (list (id 'p) (id 'q))))))))) 
                (bool #t)) 
           (bool #f)))
(test (desugar (parse expr24))
      (app (fun 'a (app (fun 'b (num 17)) (op / (list (id 'a) (num 0))))) (num 2)))
(test (desugar (parse expr25))
      (app (fun 'x (num 1)) (op sub1 (list (fun 'x (id 'x))))))

;; Pruebas interp :: interp
(test/exn (interp (desugar (parse expr1)) (mtSub)) "Variable libre")
(test (interp (desugar (parse expr2)) (mtSub)) (numV 1729))
(test (interp (desugar (parse expr3)) (mtSub)) (numV 6))
(test (interp (desugar (parse expr4)) (mtSub)) (numV -4))
(test (interp (desugar (parse expr5)) (mtSub)) (numV 6))
(test (interp (desugar (parse expr6)) (mtSub)) (numV 1/6))
(test (interp (desugar (parse expr7)) (mtSub)) (numV 0))
(test (interp (desugar (parse expr8)) (mtSub)) (numV 8))
(test (interp (desugar (parse expr9)) (mtSub)) (numV 18))
(test (interp (desugar (parse expr10)) (mtSub)) (numV 28))
(test (interp (desugar (parse expr11)) (mtSub)) (numV 5))
(test (interp (desugar (parse expr12)) (mtSub)) (exprV (op + (list (id 'a) (id 'a))) (mtSub)))
(test (interp (desugar (parse expr13)) (mtSub)) 
      (exprV (op + (list (id 'a) (id 'a))) (aSub 'a (exprV (num 2) (mtSub)) (mtSub))))
(test (interp (desugar (parse expr14)) (mtSub)) (exprV (id 'a) (mtSub)))
(test/exn (interp (desugar (parse expr15)) (mtSub)) "Variable libre")
(test (interp (desugar (parse expr16)) (mtSub)) 
      (closureV 'b (fun 'h (op / (list (op * (list (id 'b) (id 'h))) (num 2)))) (mtSub)))
(test (interp (desugar (parse expr17)) (mtSub)) (numV 10))
(test (interp (desugar (parse expr18)) (mtSub)) (exprV (bool #t) (mtSub)))
(test (interp (desugar (parse expr19)) (mtSub)) (exprV (bool #f) (mtSub)))
(test (interp (desugar (parse expr20)) (mtSub)) (numV 2))
(test (interp (desugar (parse expr21)) (mtSub)) (numV 4))
(test (interp (desugar (parse expr22)) (mtSub)) (boolV #f))
(test (interp (desugar (parse expr23)) (mtSub)) (boolV #f))
(test (interp (desugar (parse expr24)) (mtSub)) (numV 17))
(test (interp (desugar (parse expr25)) (mtSub)) (numV 1))
